-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 10:13:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT NULL,
  `uname` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `categories_id` INT NOT NULL,
  `categories_name` VARCHAR(45) NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `articleid` INT NOT NULL,
  `articleceContent` LONGTEXT NULL,
  `articleTitle` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`articleid`),
  INDEX `fk_article_user1_idx` (`user_id` ASC),
  INDEX `fk_article_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`categories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_user` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_user1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_user1` (
  `user_iduser` INT NOT NULL,
  `user_iduser1` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `user_iduser1`),
  INDEX `fk_user_has_user1_user1_idx` (`user_iduser1` ASC),
  INDEX `fk_user_has_user1_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_user1_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user1_user1`
    FOREIGN KEY (`user_iduser1`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userComment` (
  `reviewern_id` INT NOT NULL,
  `byreviewers_id` INT NOT NULL,
  `comment` LONGTEXT NULL,
  INDEX `fk_user_has_user2_user2_idx` (`byreviewers_id` ASC),
  INDEX `fk_user_has_user2_user1_idx` (`reviewern_id` ASC),
  PRIMARY KEY (`reviewern_id`, `byreviewers_id`),
  CONSTRAINT `fk_user_has_user2_user1`
    FOREIGN KEY (`reviewern_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user2_user2`
    FOREIGN KEY (`byreviewers_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_comment` (
  `user_iduser` INT NOT NULL,
  `article_articleid` INT NOT NULL,
  `comment` LONGTEXT NULL,
  PRIMARY KEY (`user_iduser`, `article_articleid`),
  INDEX `fk_user_has_article_article1_idx` (`article_articleid` ASC),
  INDEX `fk_user_has_article_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_article_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_article_article1`
    FOREIGN KEY (`article_articleid`)
    REFERENCES `mydb`.`article` (`articleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
